# Generated by Django 4.0.2 on 2022-03-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_liveresult_imageresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageresult',
            old_name='Deformity_Res_Img1',
            new_name='imgRes1',
        ),
        migrations.RenameField(
            model_name='imageresult',
            old_name='Deformity_Res_Img2',
            new_name='imgRes2',
        ),
        migrations.RenameField(
            model_name='liveresult',
            old_name='Deformity_Res_Live1',
            new_name='LiveRes1',
        ),
        migrations.RenameField(
            model_name='liveresult',
            old_name='Deformity_Res_Live2',
            new_name='LiveRes2',
        ),
    ]
