# Generated by Django 4.0.2 on 2022-03-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_deformity_res_img1_imageresult_imgres1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resu', models.CharField(max_length=255)),
            ],
        ),
    ]
