# Generated by Django 4.0.2 on 2022-03-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Rep', models.CharField(max_length=255)),
                ('Report1', models.CharField(max_length=255)),
            ],
        ),
    ]
