# Generated by Django 4.0.2 on 2022-03-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Testing',
        ),
        migrations.RenameField(
            model_name='imageresult',
            old_name='imgRes1',
            new_name='ImgLeftAngle',
        ),
        migrations.RenameField(
            model_name='imageresult',
            old_name='imgRes2',
            new_name='ImgRightAngle',
        ),
        migrations.RenameField(
            model_name='liveresult',
            old_name='LiveRes1',
            new_name='LiveLeftAngle',
        ),
        migrations.RenameField(
            model_name='liveresult',
            old_name='LiveRes2',
            new_name='LiveRightAngle',
        ),
    ]
