# Generated by Django 4.0.2 on 2022-03-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_report_delete_testing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ImgLeftAngle', models.CharField(max_length=255)),
                ('ImgRightAngle', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='liveresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='imageResult',
        ),
        migrations.DeleteModel(
            name='liveResult',
        ),
    ]
