# Generated by Django 4.0.2 on 2022-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_liveres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('forget_token', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
